import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const user = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar user={user} />
        <main>
          <div className="">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
