import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Montserrat, Catamaran } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  weight: ["400", "500"],
  style: ["normal"],
  subsets: ["latin"],
});

const catamaran = Catamaran({
  weight: ["200"],
  style: ["normal"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  const user = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar user={user} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
