name: plutzy deploy
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: no se que
        uses: actions/setup-node@v3
      - name: instalar dependencias
        run: npm i
      - name: Bundle
        run: npm run build
