name: plutzy deploy
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: no se que
      #   uses: actions/setup-node@v2
      - name: instalar dependencias
        run: npm i
      - name: Run Eslint
        run: npm run ci:lint
      - name: Bundle
        run: npm run build
